In [7]:
import xarray as xr
import numpy as np

In [8]:
data = xr.open_dataset('air.mon.mean.nc')

In [35]:
data["lon"][0]

<xarray.DataArray 'lon' ()>
array(0., dtype=float32)
Coordinates:
    lon      float32 0.0
Attributes:
    units:          degrees_east
    long_name:      Longitude
    actual_range:   [  0.  357.5]
    standard_name:  longitude
    axis:           X

In [26]:
data["air"].sel(level=500).sel(time='1948-01-01T00:00:00.000000000')

<xarray.DataArray 'air' (lat: 73, lon: 144)>
array([[-44.510002, -44.510002, -44.510002, ..., -44.510002, -44.510002,
        -44.510002],
       [-43.760002, -43.72999 , -43.69999 , ..., -43.85    , -43.82    ,
        -43.77999 ],
       [-42.329994, -42.30999 , -42.299995, ..., -42.41999 , -42.379997,
        -42.35    ],
       ...,
       [-34.96    , -34.999992, -35.049995, ..., -34.80999 , -34.869987,
        -34.909996],
       [-35.249992, -35.27999 , -35.30999 , ..., -35.15    , -35.18    ,
        -35.21    ],
       [-35.21    , -35.21    , -35.21    , ..., -35.21    , -35.21    ,
        -35.21    ]], dtype=float32)
Coordinates:
    level    float32 500.0
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... -82.5 -85.0 -87.5 -90.0
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
    time     datetime64[ns] 1948-01-01
Attributes:
    long_name:     Monthly Mean of Air temperature
    units:         degC
    precision:     2
    var_desc:      Air Temperature
    level_desc:    Multiple levels
    statistic:     Mean
    parent_stat:   Other
    valid_range:   [-200.  300.]
    dataset:       NCEP Reanalysis Derived Products
    actual_range:  [-108.64999    43.959667]

In [36]:
res = [i for i in data.data_vars] 

In [37]:
res

['air']

In [1]:
import plot_meteo as pm

In [2]:
data_test = pm.quick_view('air.mon.mean.nc')

In [3]:
data_test.Resume()

Dimension time: 
<xarray.DataArray 'time' (time: 869)>
array(['1948-01-01T00:00:00.000000000', '1948-02-01T00:00:00.000000000',
       '1948-03-01T00:00:00.000000000', ..., '2020-03-01T00:00:00.000000000',
       '2020-04-01T00:00:00.000000000', '2020-05-01T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1948-01-01 1948-02-01 ... 2020-05-01
Attributes:
    long_name:        Time
    delta_t:          0000-01-00 00:00:00
    avg_period:       0000-01-00 00:00:00
    prev_avg_period:  0000-00-01 00:00:00
    standard_name:    time
    axis:             T
    actual_range:     [1297320. 1931376.]
--------------------------
Dimension level: 
<xarray.DataArray 'level' (level: 17)>
array([1000.,  925.,  850.,  700.,  600.,  500.,  400.,  300.,  250.,  200.,
        150.,  100.,   70.,   50.,   30.,   20.,   10.], dtype=float32)
Coordinates:
  * level    (level) float32 1e+03 925.0 850.0 700.0 ... 50.0 30.0 20.0 10.0
Attributes:
    units:  

In [1]:
import plot_meteo as pm
data_test = pm.quick_view('air.mon.mean.nc')
data_test.first_plot("air",'1948-03-01T00:00:00.000000000',500)

Entrer un path pour save les figures: iok
Select your projection: 1-PlateCarree, 2-AlbersEqualArea, 3-AzimuthalEquidistant, 4-LambertConformal, 5-LambertCylindrical, 6-Mercator, 7-Miller, 8-Mollweide, 9-Orthographic, 10-Orthographic, 11-Robinson, 12-Sinusoidal, 13-Stereographic, 14-TransverseMercator, 15-UTM, 16-InterruptedGoodeHomolosine, 17-RotatedPole, 18-OSGB, 19-EuroPP, 20-Geostationary, 21-NearsidePerspective, 22-Gnomonic, 23-LambertAzimuthalEqualArea, 24-NorthPolarStereo, 25-OSNI, 26-SouthPolarStereo.
6


TypeError: Cannot label Stereographic gridlines. Only PlateCarree gridlines are currently supported.

<Figure size 792x612 with 2 Axes>

In [3]:
import numpy as np
np.arange(-90,90,10)

array([-90, -80, -70, -60, -50, -40, -30, -20, -10,   0,  10,  20,  30,
        40,  50,  60,  70,  80])